"""
JobBot Configuration
All keywords, company lists, filter rules, and settings.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ─── API Keys & Credentials ────────────────────────────────────────
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS", "")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD", "")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL", "harry.cammer@gmail.com")

# ─── Title Keywords (what the role is called) ───────────────────────
TITLE_KEYWORDS = [
    "product marketing",
    "pmm",
    "growth marketing",
    "marketing manager",
    "marketing lead",
    "head of marketing",
    "brand marketing",
    "content marketing",
    "ecosystem marketing",
    "protocol marketing",
    "director of marketing",
    "director, marketing",
    "vp marketing",
    "vp of marketing",
    "vp, marketing",
    "vice president marketing",
    "gtm",
    "go-to-market",
    "go to market",
    "cmo",
    "chief marketing officer",
    "marketing director",
    "senior marketing",
    "staff marketing",
    "principal marketing",
    "communications manager",
    "communications lead",
    "head of communications",
    "developer relations",
    "devrel",
    "community marketing",
]

# ─── Industry Keywords (what makes it crypto/web3/AI/agentic) ───────
INDUSTRY_KEYWORDS = [
    # Crypto / Web3
    "crypto",
    "cryptocurrency",
    "blockchain",
    "web3",
    "defi",
    "decentralized finance",
    "digital assets",
    "digital currency",
    "nft",
    "dao",
    "stablecoin",
    "tokenomics",
    "token",
    "protocol",
    "layer 1",
    "layer 2",
    "l1",
    "l2",
    "ethereum",
    "solana",
    "bitcoin",
    "fintech",
    "onchain",
    "on-chain",
    "smart contract",
    "dapp",
    "dex",
    "cefi",
    "wallet",
    "custody",
    # Agentic / AI Payments / Agent Commerce
    "agentic",
    "ai agent",
    "ai agents",
    "agent commerce",
    "agent-to-agent",
    "a2a",
    "agent payments",
    "agent protocol",
    "autonomous agent",
    "multi-agent",
    "multiagent",
    "mcp",
    "model context protocol",
    "agent framework",
    "agent infrastructure",
    "agent orchestration",
    "ai payments",
    "machine-to-machine",
    "m2m payments",
    "programmable payments",
    "payment rails",
    # Payments / Stablecoins / Trad Rails Moving to Blockchain
    "stablecoin payments",
    "crypto payments",
    "digital payments",
    "payment infrastructure",
    "cross-border payments",
    "real-time payments",
    "tokenized payments",
    "embedded finance",
    "open banking",
    # AI (broader, but filtered strictly)
    "artificial intelligence",
    "ai ",
    "llm",
    "machine learning",
    "generative ai",
]

# ─── Location Filters ───────────────────────────────────────────────
ACCEPTED_LOCATIONS = [
    "remote",
    "anywhere",
    "worldwide",
    "global",
    "distributed",
    "work from home",
    "wfh",
    "new york",
    "nyc",
    "ny",
    "manhattan",
    "brooklyn",
    "united states",
    "usa",
    "us",
]

# ─── Exclusion Filters ──────────────────────────────────────────────
EXCLUDED_LEVELS = [
    "junior",
    "jr.",
    "jr ",
    "entry level",
    "entry-level",
    "associate",
    "intern ",
    "internship",
    "graduate",
    "new grad",
]

EXCLUDED_TYPES = [
    "contract",
    "freelance",
    "part-time",
    "part time",
    "temporary",
    "contractor",
]

# Staffing agencies and recruiters - these are never direct-hire quality roles
EXCLUDED_COMPANIES = [
    "creative circle",
    "robert half",
    "robert half international",
    "kforce",
    "teksystems",
    "tek systems",
    "hays",
    "randstad",
    "adecco",
    "manpower",
    "manpowergroup",
    "kelly services",
    "insight global",
    "aston carter",
    "beacon hill",
    "staffing",
    "recruiting agency",
    "talent solutions",
    "hired",
    "toptal",
    "aquent",
    "onward search",
    "24 seven",
    "mondo",
    "vitamin t",
    "the creative group",
    "cella",
    "yoh",
    "allegis",
    "spherion",
]

# Minimum salary threshold (lenient since roles negotiate up)
MIN_SALARY = 140_000

# Only include jobs posted within this many hours
MAX_AGE_HOURS = 48

# ─── Blue-Chip Companies ────────────────────────────────────────────
# The "gold standard" list - established, PMF, not going anywhere.
# Used for: (1) AI scoring boost, (2) "New at Top Companies" email section

TOP_COMPANIES = [
    # --- Exchanges ---
    "Coinbase",
    "Kraken",
    "Gemini",
    "Binance",
    "OKX",
    "Crypto.com",
    "Bybit",
    "Bitstamp",
    # --- DEX / DeFi Protocols ---
    "Uniswap",
    "Uniswap Labs",
    "Hyperliquid",
    "Aave",
    "Aave Labs",
    "Avara",
    "dYdX",
    "MakerDAO",
    "Sky",
    "Lido",
    "Lido Finance",
    "Curve",
    "Curve Finance",
    "Jupiter",
    "Pendle",
    "Pendle Finance",
    "Compound",
    "Compound Finance",
    "Synthetix",
    "Ethena",
    "Ethena Labs",
    "Morpho",
    "Morpho Labs",
    "Yearn",
    "1inch",
    "Raydium",
    "Balancer",
    "Aerodrome",
    "Velodrome",
    "Benqi",
    "GMX",
    "Drift",
    "Drift Protocol",
    "Marinade",
    "Jito",
    "Jito Labs",
    "Kamino",
    "Maple Finance",
    "Maple",
    "Sommelier",
    "Instadapp",
    "Spark",
    "Spark Protocol",
    # --- L1 / L2 Protocols & Labs ---
    "Solana Labs",
    "Solana Foundation",
    "Solana",
    "Ava Labs",
    "Avalanche",
    "Polygon",
    "Polygon Labs",
    "Offchain Labs",
    "Arbitrum",
    "Arbitrum Foundation",
    "OP Labs",
    "Optimism",
    "Optimism Foundation",
    "Consensys",
    "ConsenSys",
    "Mysten Labs",
    "Sui",
    "StarkWare",
    "Starknet",
    "StarkNet",
    "NEAR",
    "NEAR Foundation",
    "Aptos",
    "Aptos Labs",
    "Base",
    "Sei Labs",
    "Sei",
    "Monad",
    "Monad Labs",
    "Category Labs",
    "Celestia",
    "Celestia Labs",
    "EigenLayer",
    "Eigen Labs",
    "Scroll",
    "zkSync",
    "Matter Labs",
    "Aztec",
    "Aztec Labs",
    "Berachain",
    "Movement Labs",
    "Movement",
    "Eclipse",
    "Fuel Labs",
    "Fuel",
    "Linea",
    "Mantle",
    "Mantle Network",
    "Blast",
    "Mode Network",
    "Mode",
    "Zora",
    "Zora Labs",
    # --- Cross-Chain / Interoperability ---
    "Wormhole",
    "Wormhole Labs",
    "LayerZero",
    "LayerZero Labs",
    "Axelar",
    "Across Protocol",
    "Across",
    "Stargate",
    "Connext",
    # --- Stablecoins ---
    "Circle",
    "Tether",
    "Paxos",
    "Ethena Labs",
    "Agora",
    "Mountain Protocol",
    # --- Custody / Institutional Infrastructure ---
    "Anchorage Digital",
    "Anchorage",
    "Fireblocks",
    "BitGo",
    "Copper",
    "Copper.co",
    "Fidelity Digital Assets",
    "Galaxy Digital",
    "Galaxy",
    "Cumberland",
    "B2C2",
    "Wintermute",
    "GSR",
    "Amber Group",
    "Hashnote",
    # --- Developer Infrastructure / Tooling ---
    "Alchemy",
    "QuickNode",
    "Chainlink",
    "Chainlink Labs",
    "ENS",
    "ENS Labs",
    "The Graph",
    "Blockdaemon",
    "Figment",
    "Infura",
    "Helius",
    "Tenderly",
    "Gelato",
    "Gelato Network",
    "Biconomy",
    "Safe",
    "Safe Global",
    "Gnosis",
    "Gnosis Chain",
    "Privy",
    "Dynamic",
    "Thirdweb",
    "RedStone",
    # --- Security / Analytics / Compliance ---
    "Chainalysis",
    "TRM Labs",
    "Elliptic",
    "Nansen",
    "Dune",
    "Dune Analytics",
    "Gauntlet",
    "OpenZeppelin",
    "Certik",
    "Trail of Bits",
    "Forta",
    "Sardine",
    # --- Wallets / Consumer ---
    "Phantom",
    "Ledger",
    "MetaMask",
    "OpenSea",
    "Blur",
    "Magic Eden",
    "Rainbow",
    "Exodus",
    "Trezor",
    "Backpack",
    "Galxe",
    "Layer3",
    "Rabbithole",
    # --- Data / Research ---
    "Messari",
    "CoinGecko",
    "The Block",
    "Kaiko",
    "Coin Metrics",
    "Artemis",
    # --- Media ---
    "Blockworks",
    "CoinDesk",
    "Decrypt",
    # --- VC / Investment ---
    "a16z crypto",
    "a16z",
    "Andreessen Horowitz",
    "Paradigm",
    "Pantera",
    "Pantera Capital",
    "Polychain",
    "Polychain Capital",
    "Dragonfly",
    "Multicoin Capital",
    "Multicoin",
    "Variant",
    "Variant Fund",
    "Electric Capital",
    "Framework Ventures",
    "Placeholder",
    "Blockchain Capital",
    "Digital Currency Group",
    "DCG",
    "Grayscale",
    # --- Other Established Crypto Players ---
    "Animoca Brands",
    "Yuga Labs",
    "Immutable",
    "21Shares",
    "21.co",
    "Bitwise",
    "VanEck",
    "Securitize",
    "Marathon Digital",
    "MARA",
    "Core Scientific",
    "Riot Platforms",
    "Robinhood Crypto",
    "Robinhood",
    "Worldcoin",
    "Tools for Humanity",
    "Tempo",
    # --- Payments / Stablecoins / Trad Rails Moving to Blockchain ---
    "Stripe",
    "PayPal",
    "Visa",
    "Mastercard",
    "Plaid",
    "Block",
    "Square",
    "Cash App",
    "Adyen",
    "Checkout.com",
    "Marqeta",
    "MoonPay",
    "Transak",
    "Ramp Network",
    "Zero Hash",
    "BVNK",
    "Bridge",
    "Mesh",
    "Nuvei",
    "Airwallex",
    "dLocal",
    "Payoneer",
    "Wise",
    "Tassat",
    "Wyre",
    "Rain",
    "Conduit",
    "Mural",
    "Stables",
    "Sphere",
    "Sequence",
    "Lightspark",
    "Thunes",
    "Turnkey",
    "Crossmint",
    "RedotPay",
    "Figure",
    "Cross River",
    "Cross River Bank",
    "Catena Labs",
    "Stellar",
    "Stellar Development Foundation",
    "Deel",
    # --- Agentic / AI Agent Infrastructure ---
    "Anthropic",
    "OpenAI",
    "Sierra",
    "Adept",
    "Imbue",
    "LangChain",
    "LangSmith",
    "CrewAI",
    "E2B",
    "Letta",
    "Lindy AI",
    "Lindy",
    "Relevance AI",
    "Wordware",
    "Skyfire",
    "Nevermined",
    "Fetch.ai",
    "ASI Alliance",
    "Autonolas",
    "OLAS",
    "Virtuals Protocol",
    "Virtuals",
    "NEAR AI",
    "PayOS",
    "Nekuda",
    "Perplexity",
    "Ramp AI",
    "Coinbase Developer Platform",
    "commercetools",
]

# Normalized set for fast lookup (lowercase)
TOP_COMPANIES_SET = {c.lower() for c in TOP_COMPANIES}

# ─── ATS Board Configurations ──────────────────────────────────────
# Greenhouse: boards-api.greenhouse.io/v1/boards/{slug}/jobs
GREENHOUSE_BOARDS = {
    "Coinbase": "coinbase",
    "Uniswap Labs": "uniswaplabs",
    "Fireblocks": "fireblocks",
    "BitGo": "bitgo",
    "Gemini": "gemini",
    "Ava Labs": "avalabs",
    "Alchemy": "alchemy",
    "Circle": "circle",
    "OKX": "okx",
    "TRM Labs": "trmlabs",
    "dYdX": "dydx",
    "Copper": "copper",
    "Galaxy Digital": "galaxydigitalservices",
    "Solana Labs": "solanalabs",
    "Consensys": "consensys",
    "Figment": "figment",
    "Aptos Labs": "aptoslabs",
    "OpenZeppelin": "openzeppelin",
    "Paxos": "paxos",
    "Immutable": "immutable",
    "Yuga Labs": "yugalabs",
    # New additions
    "Plaid": "plaid",
    "Stripe": "stripe",
    "Visa": "visa",
    "Mastercard": "mastercard",
    "Ethena Labs": "ethenalabs",
    "MoonPay": "moonpay",
    "Wormhole": "wormholelabs",
    "LayerZero Labs": "layerzerolabs",
    "Safe": "safeglobal",
    "Worldcoin": "worldcoinorg",
    "Tools for Humanity": "worldcoinorg",
    "Magic Eden": "magiceden",
    "Nansen": "nansen",
    "Biconomy": "biconomy",
    "Anthropic": "anthropic",
    "OpenAI": "openai",
    "Sierra": "sierraai",
    "Adyen": "adyen",
    "Robinhood": "robinhood",
    "Animoca Brands": "animocabrands",
    "Lido": "lido",
    "Galxe": "galxe",
    "Zero Hash": "zerohash",
    "Stellar": "stellar",
    "Thunes": "thunes",
    "Lightspark": "lightspark",
    "Figure": "figure",
}

# Lever: api.lever.co/v0/postings/{slug}
LEVER_BOARDS = {
    "Anchorage Digital": "anchorage",
    "Aave Labs": "aavelabs",
    "Ledger": "ledger",
    "Offchain Labs": "offchainlabs",
    "Crypto.com": "crypto",
    "Chainlink Labs": "chainlinklabs",
    "Protocol Labs": "protocol",
    "Bitwise": "bitwiseinvestments",
    "Securitize": "securitize",
    "Dune Analytics": "daboralabs",
    # New additions
    "Ethena Labs": "ethenalabs",
    "Drift": "driftprotocol",
    "Maple Finance": "maplefinance",
    "Messari": "messari",
    "Wintermute": "wintermute-trading",
    "Gelato": "gelato",
    "Trail of Bits": "trailofbits",
    "Blockdaemon": "blockdaemon",
    "Perplexity": "perplexity-ai",
    "Checkout.com": "checkoutcom",
    "Nuvei": "nuvei",
    "BVNK": "bvnk",
    "Airwallex": "airwallex",
    "Conduit": "conduit",
    "Rain": "rain",
    "Crossmint": "crossmint",
    "Deel": "deel",
    "Mesh": "meshconnect",
    "Turnkey": "turnkey",
}

# Ashby: api.ashby.io/posting-api/job-board/{slug}
ASHBY_BOARDS = {
    "Kraken": "Kraken",
    "Chainalysis": "Chainalysis",
    "Phantom": "Phantom",
    "Polygon Labs": "Polygon%20Labs",
    "Solana Foundation": "Solana%20Foundation",
    "Optimism": "Optimism",
    "OP Labs": "OP%20Labs",
    "Mysten Labs": "MystenLabs",
    "QuickNode": "QuickNode",
    "Blockworks": "Blockworks",
    "ENS Labs": "ENS%20Labs",
    "OpenSea": "OpenSea",
    "Hyperliquid": "Hyperliquid",
    "Monad": "Monad",
    "EigenLayer": "EigenLabs",
    "Scroll": "Scroll",
    "Matter Labs": "MatterLabs",
    # New additions
    "Berachain": "Berachain",
    "Movement Labs": "Movement%20Labs",
    "Celestia": "Celestia%20Labs",
    "StarkWare": "StarkWare",
    "Morpho": "Morpho%20Labs",
    "Pendle": "Pendle",
    "Jito Labs": "Jito%20Labs",
    "Privy": "Privy",
    "Thirdweb": "thirdweb",
    "Aztec": "Aztec",
    "Backpack": "Backpack",
    "Across Protocol": "Across%20Protocol",
    "The Graph": "The%20Graph",
    "Sardine": "Sardine",
    "Marqeta": "Marqeta",
    "Zero Hash": "Zero%20Hash",
    "Skyfire": "Skyfire",
    "CrewAI": "CrewAI",
    "LangChain": "LangChain",
}

# ─── JobSpy Search Queries ──────────────────────────────────────────
# Each query is a (search_term, site_name_filter) pair.
# We run multiple queries to maximize coverage.
JOBSPY_QUERIES = [
    # Crypto / Web3
    "product marketing crypto",
    "product marketing blockchain",
    "product marketing web3",
    "product marketing digital assets",
    "product marketing defi",
    "marketing manager crypto",
    "marketing manager blockchain",
    "marketing manager web3",
    "growth marketing crypto",
    "growth marketing web3",
    "head of marketing crypto",
    "head of marketing web3",
    "PMM crypto",
    "PMM blockchain",
    "PMM web3",
    "marketing lead crypto",
    "marketing lead web3",
    "marketing director crypto",
    "marketing director blockchain",
    # Agentic / AI Payments
    "product marketing agentic",
    "product marketing AI agents",
    "product marketing AI payments",
    "marketing manager AI agents",
    "PMM agentic",
    "marketing agentic commerce",
    "marketing agent infrastructure",
    "product marketing autonomous agents",
    # Payments / Stablecoins / Trad Rails
    "product marketing stablecoins",
    "product marketing crypto payments",
    "product marketing digital payments",
    "PMM payments blockchain",
    "marketing manager stablecoins",
    # AI (general)
    "product marketing AI",
    "product marketing artificial intelligence",
]

# ─── Email Settings ─────────────────────────────────────────────────
EMAIL_SUBJECT_PREFIX = "JobBot Daily"
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

# ─── Scoring ────────────────────────────────────────────────────────
SCORING_MODEL = "claude-sonnet-4-5-20250929"
MIN_RELEVANCE_SCORE = 6
SCORING_BATCH_SIZE = 20  # Jobs per API call

# ─── Database ───────────────────────────────────────────────────────
DB_PATH = os.path.join(os.path.dirname(__file__), "jobbot.db")
